title: Donatien Konan | Data Science, AI (ML/DL/LLM) Portfolio
logo: assets/img/profile.jpg
description: "A portfolio showcasing my work in data science, data engineering and AI (ML/DL/LLM) projects."
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme  # Ensure this is included to use the remote theme
  - jekyll-sass-converter
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
permalink: pretty
sass:
  style: compressed #########################
# Enable asset pipeline
include:
  - assets/css

# Optional social links for the footer (customized with your actual URLs)
social_links:
  - title: "GitHub"
    url: https://github.com/donat-konan33
  - title: "LinkedIn"
    url: https://www.linkedin.com/in/donat-konan33

# Optional footer links
footer_links:
  - title: "Live Portfolio"
    url: https://donat-konan33.github.io

# Additional settings
paginate: 5
